config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboard#index"
    resources :football_news
    resources :users  do
      patch "confirm_user", on: :member
    end
    resources :leagues do
      resources :teams, only: [:create, :destroy]
    end
    resources :teams do
      member do
        patch "set_league"
        get "load_players_by_team"
      end
      resources :player_infos, path: "player", except: %i(index new)
    end
    resources :rounds
    resources :countries
    resources :continents do
      get "load_countries", on: :member
    end
    resources :matches do
      get "load_rounds_and_teams", on: :collection
    end
    resources :match_infos, except: %i(index show new)
    resources :score_sugests, only: %i(create update destroy)
    resources :player_infos, path: "players" do
      patch "set_player_by_team", on: :member
    end
    resources :rankings, only: :update
    resources :score_bets, only: %i(index update)
    resources :notifies, only: :index
    resources :credits do
      patch "quick_set_type", on: :member
    end
    resources :match_results, only: %i(create update destroy)
  end

  root "home#index"

  devise_for :users

  post "upload_image" => "upload_froala#upload_image_froala", as: :upload_image

  resources :users, only: [:show, :edit, :update]
  resources :football_news, only: [:index, :show]
  resources :comment, only: :create
  resources :score_bets, only: :create
  resources :teams, only: :index do
    get "load_countries", on: :collection
    get "/search", to: "teams#search", on: :collection
    get "/details", to: "teams#details", on: :collection
  end
  resources :rankings, only: [:index, :show]
end

app/models/match.rb
class Match < ApplicationRecord
  acts_as_paranoid
  enum status: [:pending, :ready, :finish]

  belongs_to :team1, class_name: Team.name
  belongs_to :team2, class_name: Team.name
  belongs_to :round
  has_many :match_infos, dependent: :destroy
  has_many :score_sugests, dependent: :destroy
  has_many :match_results, dependent: :destroy
  has_many :score_bets, dependent: :destroy

  validates :team1_id, presence: true
  validates :team2_id, presence: true
  validates :round_id, presence: true
  validate :check_team_eq

  scope :newest, ->{order date_of_match: :desc}
  scope :ranger_date, (lambda do
    where("date_of_match <= ?", Date.today + Settings.day.days)
  end)

  delegate :name, to: :team1, prefix: true
  delegate :name, to: :team2, prefix: true
  delegate :name, to: :round, prefix: true

  def check_team_eq
    errors.add(:team, I18n.t("not_equal")) if team1_id == team2_id
  end

  def load_rounds
    return [[round_name, round_id]] if id.present?
    []
  end

  def load_teams
    return [[team1_name, team1_id], [team2_name, team2_id]] if id.present?
    []
  end

  def load_teams_match_infos
    [[team1_name, team1_id], [team2_name, team2_id]]
  end

  def get_score_team1
    match_results.find_by team_id: team1_id
  end

  def get_score_team2
    match_results.find_by team_id: team2_id
  end

  def check_finish_match
    return unless score_bets.present?
    score_bets.each do |s|
      sugest = [s.score_sugest_score_win, s.score_sugest_score_lost]
      if sugest == format_score_match
        send_mail_after_match_end s, sugest
      else
        s.lost!
        s.user.send_match_info_lost sugest, s
      end
    end
  end

  def send_mail_after_match_end bet, sugest
    bet.win!
    money_win = (bet.score_sugest.ratio.to_i * bet.price.to_f)
    new_money = bet.user.money.to_f + money_win
    bet.user.update_attributes money: new_money
    bet.user.send_bet_info_match_info money_win, sugest, bet
  end

  def format_score_match
    [get_score_team1.score, get_score_team2.score]
  end

  class << self
    def load_leagues
      League.newest.pluck(:name, :id)
    end

    def select_status
      statuses.map{|c| [c[0].titleize, c[0]]}
    end
  end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < Admin::BaseController
  load_and_authorize_resource
  before_action :load_match, only: %i(edit update destroy load_infos)
  before_action :load_infos, only: :edit

  def index
    @q = Match.newest.includes(:team1, :team2).ransack params[:q]
    @matches = @q.result.page(params[:page]).per Settings.match_per
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new match_params
    if @match.save
      flash[:info] = t ".success"
      redirect_to admin_matches_path
    else
      flash[:danger] = t ".error"
      render :new
    end
  end

  def edit; end

  def update
    @old_status = @match.finish?
    if @match.update_attributes match_params
      @match.check_finish_match if @old_status == false && @match.finish?
      flash[:info] = t ".success"
      redirect_to admin_matches_path
    else
      flash[:danger] = t ".error"
      render :edit
    end
  rescue ActiveRecord::RecordInvalid => ex
    flash[:danger] = ex.record.errors
    render :edit
  end

  def destroy
    if @match.destroy
      flash[:info] = t ".success"
    else
      flash[:danger] = t ".error"
    end
    redirect_to admin_matches_path
  end

  def load_rounds_and_teams
    @rounds = Round.by_league(params[:league_id]).pluck(:name, :id) || []
    @teams = Team.by_league(params[:league_id]).pluck(:name, :id) || []
    render json: {rounds: @rounds, teams: @teams}
  end

  private

  def load_match
    @match = Match.find params[:id]
  end

  def load_infos
    @match_infos =
      @match.match_infos.newest.page(params[:match_page]).per Settings.info_per
    @score_sugests =
      @match.score_sugests.newest.page(params[:sugest]).per Settings.sugest_per
    @match_results = @match.match_results
    @match_info = @match.match_infos.build
    @score_sugest = @match.score_sugests.build
  end

  def match_params
    params.require(:match).permit :date_of_match, :extra_time1,
      :extra_time2, :time, :team1_id, :team2_id, :round_id, :status
  end
end

app/helpers/matchs_helper.rb
module MatchsHelper
  def format_score result
    return "?" unless result.present?
    result.score
  end

  def format_match_ready match
    return "FT" if match.finish?
    return if match.pending?
    "<span class='minute_blink'>#{match.time}'</span>" if match.ready?
  end

  def format_league_and_round_name round
    "<b>#{round.league_name}</b> - #{round.name}"
  end

  def format_score_sugest sugest
    "#{sugest.score_win} - #{sugest.score_lost}"
  end
end

app/views/admin/matches/_form.html.erb
<%= form_for @match, url: url do |f| %>
  <%= render "shared/admin/error_messages", object: f.object %>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label t ".date_of_match", class: "control-label" %>
      <%= f.datetime_field :date_of_match, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label t ".time", class: "control-label" %>
      <%= f.number_field :time, class: "form-control", min: Settings.number_min %>
    </div>
  </div>


  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label t ".extra_time1", class: "control-label" %>
      <%= f.number_field :extra_time1, class: "form-control", min: Settings.number_min %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label t ".extra_time2", class: "control-label" %>
      <%= f.number_field :extra_time2, class: "form-control", min: Settings.number_min %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label t ".league", class: "control-label" %>
      <%= select_tag "league_id", options(Match.load_leagues), {class: "form-control", prompt: t(".blank_option")} %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label t ".round", class: "control-label" %>
      <%= f.select(:round_id, @match.load_rounds, {}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label t ".team1", class: "control-label" %>
      <%= f.select(:team1_id, @match.load_teams, {prompt: t(".select_team1")}, {class: "form-control"}) %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label t ".team2", class: "control-label" %>
      <%= f.select(:team2_id, @match.load_teams, {prompt: t(".select_team2")}, {class: "form-control"}) %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label t ".status", class: "control-label" %>
      <%= f.select(:status, Match.select_status, {}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group submit_button">
    <%= f.submit t(".submit"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/matches/_match.html.erb
<tr>
  <td><%= l match.date_of_match, format: :with_time %></td>
  <td><%= match.time %></td>
  <td><%= match.team1_name %></td>
  <td><%= match.team2_name %></td>
  <td><%= match.round_name %></td>
  <td><%= match.round.league_name %></td>
  <td><%= match.status %></td>
  <td class="td-actions text-right">
    <%= link_to edit_admin_match_path(match), class: "btn btn-success btn-link btn-xs", title: t(".edit") do %>
      <i class="fa fa-edit"></i>
    <% end %>
    <%= link_to admin_match_path(match), class: "btn btn-danger btn-link btn-xs", title: t(".remove"),
      method: :delete, data: {confirm: t(".are_you_sure")} do %>
      <i class="fa fa-times"></i>
    <% end %>
  </td>
</tr>

app/views/admin/matches/_new_match_info.html.erb
<div class="modal fade" id="match_info_matches" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xs modal-resize-top-match-info" role="document">
    <div class="modal-content">
      <%= form_for [:admin, @match_info], html: {id: "matches_match_info"} do |f| %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><%= t ".title" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="border-modal">
            <div class="form-group">
              <%= f.label t(".minutes"), class: "control-label" %>
              <%= f.number_field :minutes, class: "form-control", min: Settings.number_min %>
              <%= f.hidden_field :match_id, value: @match.id %>
            </div>
            <div class="form-group">
              <%= f.label t(".message"), class: "control-label" %>
              <%= f.text_field :message, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label t(".type"), class: "control-label" %>
              <%= f.select(:type_info, MatchInfo.load_types, {}, {class: "form-control"}) %>
            </div>
            <div class="row">
              <div class="form-group col-md-6">
                <%= f.label t(".team"), class: "control-label" %>
                <%= f.select(:team_id, @match.load_teams_match_infos, {prompt: t(".select_teams")}, {class: "form-control"}) %>
              </div>
              <div class="form-group col-md-6">
                <%= f.label t(".player"), class: "control-label" %>
                <%= f.select(:player_info_id, {}, {}, {class: "form-control"}) %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary save_match_info"><%= t ".submit" %></button>
          <button type="button" class="btn btn-secondary right" data-dismiss="modal">
            <%= t ".close" %>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/matches/_new_match_result.html.erb
<div class="modal fade" id="new_match_result" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xs modal-resize-top" role="document">
    <div class="modal-content">
      <div class="form_new">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><%= t ".title" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row border-modal">
            <div class="form-group col-md-12">
              <%= label_tag t ".teams" %>
              <%= select_tag :team_id, options(@match.load_teams_match_infos), {class: "form-control", prompt: t(".blank_option")} %>
              <%= hidden_field_tag "match_id", @match.id %>
            </div>
            <div class="form-group col-md-12">
              <%= label_tag t ".score" %>
              <%= number_field_tag :score, nil, class: "form-control", min: Settings.number_min %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary submit_match_result"><%= t ".submit" %></button>
          <button type="button" class="btn btn-secondary right" data-dismiss="modal">
            <%= t ".close" %>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/matches/_new_score_sugest.html.erb
<div class="modal fade" id="new_score_sugest" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xs modal-resize-top" role="document">
    <div class="modal-content">
      <%= form_for [:admin, @score_sugest], html: {id: "match_new_score_sugest"} do |f| %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><%= t ".title" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row border-modal">
            <div class="form-group col-md-12">
              <%= f.label t(".score_win"), class: "control-label" %>
              <%= f.number_field :score_win, class: "form-control", min: Settings.number_min %>
              <%= f.hidden_field :match_id, value: @match.id %>
            </div>
            <div class="form-group col-md-12">
              <%= f.label t(".score_lost"), class: "control-label" %>
              <%= f.number_field :score_lost, class: "form-control", min: Settings.number_min %>
            </div>
            <div class="form-group col-md-12">
              <%= f.label t(".ratio"), class: "control-label" %>
              <%= f.number_field :ratio, class: "form-control", min: Settings.number_min %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary"><%= t ".submit" %></button>
          <button type="button" class="btn btn-secondary right" data-dismiss="modal">
            <%= t ".close" %>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/matches/_search_form.html.erb
<%= search_form_for [:admin, @q], class: "form-search" do |f| %>
  <div>
    <%= f.search_field :team1_name_or_team2_name_cont, class: "form-control col-sm-5 left name_field", placeholder: t(".search") %>
    <%= f.date_field :date_of_match_lteq, class: "form-control col-sm-5 left", placeholder: t(".search_date") %>
    <%= f.submit t(".search_submit"), class: "btn btn-info search-submit" %>
    <div style="clear: both"></div>
  </div>
<% end %>

app/views/admin/matches/edit.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title"><%= t ".title" %></h4>
      </div>
      <div class="card-body">
        <%= render partial: "form", locals: {url: admin_match_path(@match)} %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">
          <%= t ".match_infos" %>
          <a class="btn btn-primary btn-xs right match_info_modal">
            <%= t ".add_new_match_info" %>
          </a>
        </h4>
      </div>
      <div class="card-body">
        <table class="table table-hover table-striped">
          <thead>
            <th><%= t ".minutes" %></th>
            <th><%= t ".message" %></th>
            <th><%= t ".type" %></th>
            <th><%= t ".team" %></th>
            <th><%= t ".player" %></th>
            <th><%= t ".time" %></th>
            <th><%= t ".action" %></th>
          </thead>
          <tbody>
            <%= render @match_infos %>
          </tbody>
        </table>
        <%= paginate @match_infos, param_name: "match_page" %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">
          <%= t ".score_sugests" %>
          <a class="btn btn-primary btn-xs right modal_new_score_sugest">
            <%= t ".add_new_score_sugest" %>
          </a>
        </h4>
      </div>
      <div class="card-body">
        <table class="table table-hover table-striped table_sugest">
          <thead>
            <th><%= t ".score_win" %></th>
            <th><%= t ".score_lost" %></th>
            <th><%= t ".ratio" %></th>
            <th><%= t ".time" %></th>
            <th><%= t ".action" %></th>
          </thead>
          <tbody>
            <%= render @score_sugests %>
          </tbody>
        </table>
        <%= paginate @score_sugests, param_name: "sugest" %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">
          <%= t ".match_result" %>
          <a class="btn btn-primary btn-xs right modal_new_match_result">
            <%= t ".add_new_match_result" %>
          </a>
        </h4>
      </div>
      <div class="card-body">
        <table class="table table-hover table-striped table_match_result">
          <thead>
            <th><%= t ".team" %></th>
            <th><%= t ".score" %></th>
            <th><%= t ".action" %></th>
          </thead>
          <tbody>
            <%= render @match_results %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= render "new_match_info" %>
<%= render "new_score_sugest" %>
<%= render "new_match_result" %>

app/views/admin/matches/index.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header ">
        <h4 class="card-title">
          <%= t ".title" %>
          <%= link_to t(".new_match"), new_admin_match_path, class: "btn btn-primary btn-xs right" %>
        </h4>
      </div>
      <div class="card-body ">
        <%= render "search_form" %>
        <table class="table table-hover table-striped">
          <thead>
            <th><%= t ".date_of_match" %></th>
            <th><%= t ".time" %></th>
            <th><%= t ".team1" %></th>
            <th><%= t ".team2" %></th>
            <th><%= t ".round" %></th>
            <th><%= t ".league" %></th>
            <th><%= t ".status" %></th>
            <th><%= t ".action" %></th>
          </thead>
          <tbody>
            <%= render @matches %>
          </tbody>
        </table>
        <%= paginate @matches %>
      </div>
    </div>
  </div>
</div>

app/views/admin/matches/new.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title"><%= t ".title" %></h4>
      </div>
      <div class="card-body">
        <%= render partial: "form", locals: {url: admin_matches_path} %>
      </div>
    </div>
  </div>
</div>