config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboard#index"
    resources :football_news
    resources :users  do
      patch "confirm_user", on: :member
    end
    resources :leagues do
      resources :teams, only: [:create, :destroy]
    end
    resources :teams do
      member do
        patch "set_league"
        get "load_players_by_team"
      end
      resources :player_infos, path: "player", except: %i(index new)
    end
    resources :rounds
    resources :countries
    resources :continents do
      get "load_countries", on: :member
    end
    resources :matches do
      get "load_rounds_and_teams", on: :collection
    end
    resources :match_infos, except: %i(index show new)
    resources :score_sugests, only: %i(create update destroy)
    resources :player_infos, path: "players" do
      patch "set_player_by_team", on: :member
    end
    resources :rankings, only: :update
    resources :score_bets, only: %i(index update)
    resources :notifies, only: :index
    resources :credits do
      patch "quick_set_type", on: :member
    end
    resources :match_results, only: %i(create update destroy)
  end

  root "home#index"

  devise_for :users

  post "upload_image" => "upload_froala#upload_image_froala", as: :upload_image

  resources :users, only: [:show, :edit, :update]
  resources :football_news, only: [:index, :show]
  resources :comment, only: :create
  resources :score_bets, only: :create
  resources :teams, only: :index do
    get "load_countries", on: :collection
    get "/search", to: "teams#search", on: :collection
    get "/details", to: "teams#details", on: :collection
  end
  resources :rankings, only: [:index, :show]
end

app/models/football_new.rb
class FootballNew < ApplicationRecord
  acts_as_paranoid
  mount_uploader :image, ImageUploader

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true

  scope :newest, ->{order created_at: :desc}
end

app/controllers/admin/football_news_controller.rb
class Admin::FootballNewsController < Admin::BaseController
  authorize_resource class: false

  before_action :load_football_new, except: %i(index new create)

  def index
    @q = FootballNew.newest.ransack params[:q]
    @football_news =
      @q.result.page(params[:page]).per(Settings.football_new_per)
  end

  def show; end

  def new
    @football_new = FootballNew.new
  end

  def create
    @football_new = FootballNew.new football_new_params
    if @football_new.save
      flash[:info] = t ".create_success"
      redirect_to admin_football_news_index_path
    else
      flash[:danger] = t ".create_error"
      render :new
    end
  end

  def edit; end

  def update
    if @football_new.update football_new_params
      flash[:info] = t ".update_success"
      redirect_to admin_football_news_index_path
    else
      flash[:danger] = t ".update_error"
      render :edit
    end
  end

  def destroy
    if @football_new.destroy
      flash[:info] = t ".destroy_success"
    else
      flash[:danger] = t ".destroy_error"
    end
    redirect_to admin_football_news_index_path
  end

  private

  def load_football_new
    @football_new = FootballNew.find_by id: params[:id]
    not_found? unless @football_new
  end

  def football_new_params
    params.require(:football_new).permit :title, :content, :image
  end
end

app/controllers/football_news_controller.rb
class FootballNewsController < ApplicationController
  layout "home"

  def index
    @football_news =
      FootballNew.newest.page(params[:page]).per(Settings.football_new_per)
  end

  def show
    @football_new = FootballNew.find params[:id]
    @comments = @football_new.comments.newest
  end
end

app/helpers/football_news_helper.rb
module FootballNewsHelper
  def new_content content
    raw content[0..200]
  end
end

app/views/football_news/_comment.html.erb
<div class="comment_right">
  <p class="message"><%= comment.message %></p>
  <h4>
    <i>
      <%= t ".author", author: comment.get_user %>
      <small><%= t".comment_date", date: format_time_post(comment.created_at) %></small>
    </i>
  </h4>
</div>
<hr class="hr">

app/views/football_news/_football_new.html.erb
<div class="row border_bottom">
  <div class="col-md-4">
    <%= image_tag default_image_football_new(football_new), class: "image" %>
  </div>
  <div class="col-md-8 news_left">
    <%= link_to football_new.title, football_news_path(football_new) %>
    <p class="date_post"><%= t".post_date", date: format_time_post(football_new.created_at) %></p>
    <p class="new_text"><%= new_content football_new.content %></p>
  </div>
</div>

app/views/football_news/index.html.erb
<% provide :title, t(".header") %>
<div class="football_new">
  <%= render @football_news %>
  <%= paginate @football_news %>
</div>

app/views/football_news/show.html.erb
<% provide :title, t(".header") %>
<div class="football_new">
  <div>
    <div class="photo">
      <%= image_tag @football_new.image.large.url, class: "photo_tag" if @football_new.image.present? %>
    </div>
    <div class="news_left border_bottom">
      <p class="title_show"><%= @football_new.title %></p>
      <p class="date_post">
        <%= t".post_date", date: format_time_post(@football_new.created_at) %>
      </p>
      <p class="new_text">
        <%= raw @football_new.content %>
      </p>
      <p>
        <%= social_share_button_tag(@football_new.title) %>
      </p>
    </div>

    <div class="comment border_bottom">
      <h5 class="btn-danger"><%= t ".comment" %></h5>
      <%= render @comments %>
    </div>

    <%= form_for @football_new.comments.build, url: comment_index_path do |f| %>
      <h5 class="btn-danger"><%= t ".add_comment" %></h5>
      <%= f.hidden_field :football_new_id, value: @football_new.id %>
      <%= f.text_area :message, placeholder: t(".place_msg"), id: "message", cols: Settings.football_news.cols, rows: Settings.football_news.rows %>
      <div>
        <%= f.submit t ".comment", class: "btn btn-danger" %>
      </div>
    <% end %>
  </div>
</div>