config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboard#index"
    resources :football_news
    resources :users  do
      patch "confirm_user", on: :member
    end
    resources :leagues do
      resources :teams, only: [:create, :destroy]
    end
    resources :teams do
      member do
        patch "set_league"
        get "load_players_by_team"
      end
      resources :player_infos, path: "player", except: %i(index new)
    end
    resources :rounds
    resources :countries
    resources :continents do
      get "load_countries", on: :member
    end
    resources :matches do
      get "load_rounds_and_teams", on: :collection
    end
    resources :match_infos, except: %i(index show new)
    resources :score_sugests, only: %i(create update destroy)
    resources :player_infos, path: "players" do
      patch "set_player_by_team", on: :member
    end
    resources :rankings, only: :update
    resources :score_bets, only: %i(index update)
    resources :notifies, only: :index
    resources :credits do
      patch "quick_set_type", on: :member
    end
    resources :match_results, only: %i(create update destroy)
  end

  root "home#index"

  devise_for :users

  post "upload_image" => "upload_froala#upload_image_froala", as: :upload_image

  resources :users, only: [:show, :edit, :update]
  resources :football_news, only: [:index, :show]
  resources :comment, only: :create
  resources :score_bets, only: :create
  resources :teams, only: :index do
    get "load_countries", on: :collection
    get "/search", to: "teams#search", on: :collection
    get "/details", to: "teams#details", on: :collection
  end
  resources :rankings, only: [:index, :show]
end

app/models/country.rb
class Country < ApplicationRecord
  acts_as_paranoid
  belongs_to :continent
  has_many :teams, dependent: :destroy
  has_many :leagues, dependent: :destroy

  scope :newest, ->{order created_at: :desc}

  delegate :name, to: :continent, prefix: true

  class << self
    def load_continents
      Continent.pluck(:name, :id)
    end
  end
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < Admin::BaseController
  load_and_authorize_resource
  before_action :load_country, except: %i(index new create)

  def index
    @q = Country.newest.includes(:continent).ransack params[:q]
    @countries = @q.result.page(params[:page]).per Settings.country_per
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new country_params
    if @country.save
      flash[:info] = t ".create_success"
      redirect_to admin_countries_path
    else
      flash[:danger] = t ".create_error"
      render :new
    end
  end

  def edit; end

  def update
    if @country.update country_params
      flash[:info] = t ".update_success"
      redirect_to admin_countries_path
    else
      flash[:danger] = t ".update_error"
      render :edit
    end
  end

  def destroy
    if @country.destroy
      flash[:info] = t ".destroy_success"
    else
      flash[:danger] = t ".destroy_error"
    end
    redirect_to admin_countries_path
  end

  private

  def load_country
    @country = Country.find params[:id]
  end

  def country_params
    params.require(:country).permit :name, :continent_id
  end
end

app/views/admin/countries/_country.html.erb
<tr>
  <td><%= count_index_list country_counter %></td>
  <td><%= country.name %></td>
  <td><%= country.continent_name %></td>
  <td><%= format_time country.created_at %></td>
  <td class="td-actions text-right">
    <%= link_to edit_admin_country_path(country), class: "btn btn-success btn-link btn-xs", title: t(".edit") do %>
      <i class="fa fa-edit"></i>
    <% end %>
    <%= link_to admin_country_path(country), class: "btn btn-danger btn-link btn-xs", title: t(".remove"),
      method: :delete, data: {confirm: t(".are_you_sure")} do %>
      <i class="fa fa-times"></i>
    <% end %>
  </td>
</tr>

app/views/admin/countries/_form.html.erb
<%= form_for @country, url: url do |f| %>
  <%= render "shared/admin/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label t ".name", class: "control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t ".continent", class: "control-label" %>
    <%= f.select(:continent_id, Country.load_continents, {}, {class: "form-control"}) %>
  </div>

  <div class="form-group submit_button">
    <%= f.submit t(".submit"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/countries/_search_form.html.erb
<%= search_form_for [:admin, @q], class: "form-search" do |f| %>
  <div>
    <%= f.search_field :name_cont, class: "form-control col-sm-5 left name_field", placeholder: t(".search") %>
    <%= f.select(:continent_id_eq, Country.load_continents, {}, {class: "form-control col-sm-5 left"}) %>
    <%= f.submit t(".search_submit"), class: "btn btn-info search-submit" %>
    <div style="clear: both"></div>
  </div>
<% end %>

app/views/admin/countries/edit.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title"><%= t ".title" %></h4>
      </div>
      <div class="card-body">
        <%= render partial: "form", locals: {url: admin_country_path(@country)} %>
      </div>
    </div>
  </div>
</div>

app/views/admin/countries/index.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">
          <%= t ".countries" %>
          <%= link_to t(".add_new"), new_admin_country_path, class: "btn btn-primary btn-xs right" %>
        </h4>
      </div>
      <div class="card-body">
        <%= render "search_form" %>
        <table class="table table-hover table-striped">
          <thead>
            <th>#</th>
            <th><%= t ".name" %></th>
            <th><%= t ".continent" %></th>
            <th><%= t ".time" %></th>
            <th><%= t ".action" %></th>
          </thead>
          <tbody>
            <%= render @countries %>
          </tbody>
        </table>
        <%= paginate @countries %>
      </div>
    </div>
  </div>
</div>

app/views/admin/countries/new.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title"><%= t ".title" %></h4>
      </div>
      <div class="card-body">
        <%= render partial: "form", locals: {url: admin_countries_path} %>
      </div>
    </div>
  </div>
</div>