config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "dashboard#index"
    resources :football_news
    resources :users  do
      patch "confirm_user", on: :member
    end
    resources :leagues do
      resources :teams, only: [:create, :destroy]
    end
    resources :teams do
      member do
        patch "set_league"
        get "load_players_by_team"
      end
      resources :player_infos, path: "player", except: %i(index new)
    end
    resources :rounds
    resources :countries
    resources :continents do
      get "load_countries", on: :member
    end
    resources :matches do
      get "load_rounds_and_teams", on: :collection
    end
    resources :match_infos, except: %i(index show new)
    resources :score_sugests, only: %i(create update destroy)
    resources :player_infos, path: "players" do
      patch "set_player_by_team", on: :member
    end
    resources :rankings, only: :update
    resources :score_bets, only: %i(index update)
    resources :notifies, only: :index
    resources :credits do
      patch "quick_set_type", on: :member
    end
    resources :match_results, only: %i(create update destroy)
  end

  root "home#index"

  devise_for :users

  post "upload_image" => "upload_froala#upload_image_froala", as: :upload_image

  resources :users, only: [:show, :edit, :update]
  resources :football_news, only: [:index, :show]
  resources :comment, only: :create
  resources :score_bets, only: :create
  resources :teams, only: :index do
    get "load_countries", on: :collection
    get "/search", to: "teams#search", on: :collection
    get "/details", to: "teams#details", on: :collection
  end
  resources :rankings, only: [:index, :show]
end

app/models/football_new.rb
class FootballNew < ApplicationRecord
  acts_as_paranoid
  mount_uploader :image, ImageUploader

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true

  scope :newest, ->{order created_at: :desc}
end

app/controllers/admin/football_news_controller.rb
class Admin::FootballNewsController < Admin::BaseController
  authorize_resource class: false

  before_action :load_football_new, except: %i(index new create)

  def index
    @q = FootballNew.newest.ransack params[:q]
    @football_news =
      @q.result.page(params[:page]).per(Settings.football_new_per)
  end

  def show; end

  def new
    @football_new = FootballNew.new
  end

  def create
    @football_new = FootballNew.new football_new_params
    if @football_new.save
      flash[:info] = t ".create_success"
      redirect_to admin_football_news_index_path
    else
      flash[:danger] = t ".create_error"
      render :new
    end
  end

  def edit; end

  def update
    if @football_new.update football_new_params
      flash[:info] = t ".update_success"
      redirect_to admin_football_news_index_path
    else
      flash[:danger] = t ".update_error"
      render :edit
    end
  end

  def destroy
    if @football_new.destroy
      flash[:info] = t ".destroy_success"
    else
      flash[:danger] = t ".destroy_error"
    end
    redirect_to admin_football_news_index_path
  end

  private

  def load_football_new
    @football_new = FootballNew.find_by id: params[:id]
    not_found? unless @football_new
  end

  def football_new_params
    params.require(:football_new).permit :title, :content, :image
  end
end

app/controllers/football_news_controller.rb
class FootballNewsController < ApplicationController
  layout "home"

  def index
    @football_news =
      FootballNew.newest.page(params[:page]).per(Settings.football_new_per)
  end

  def show
    @football_new = FootballNew.find params[:id]
    @comments = @football_new.comments.newest
  end
end

app/helpers/football_news_helper.rb
module FootballNewsHelper
  def new_content content
    raw content[0..200]
  end
end

app/views/admin/football_news/_football_new.html.erb
<tr>
  <td><%= count_index_list football_new_counter %></td>
  <td><%= image_tag football_new.image.thumb.url, class: "image_cicle" if football_new.image.present? %></td>
  <td><%= football_new.title %></td>
  <td><%= format_time football_new.created_at %></td>
  <td class="td-actions text-right">
    <%= link_to edit_admin_football_news_path(football_new), class: "btn btn-success btn-link btn-xs", title: t(".edit") do %>
      <i class="fa fa-edit"></i>
    <% end %>
    <%= link_to admin_football_news_path(football_new), class: "btn btn-danger btn-link btn-xs", title: t(".remove"),
      method: :delete, data: {confirm: t(".are_you_sure")} do %>
      <i class="fa fa-times"></i>
    <% end %>
  </td>
</tr>

app/views/admin/football_news/_form.html.erb
<%= form_for @football_new, url: url do |f| %>
  <%= render "shared/admin/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label t ".title", class: "control-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label t ".content", class: "control-label" %>
    <%= f.text_area :content, class: "form-control froalaEditor", cols: 15 %>
  </div>
  <div class="form-group">
    <%= f.label t ".image_upload", class: "control-label" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <% if @football_new.image.present? %>
    <div class="form-group">
      <%= f.label t ".image", class: "control-label" %>
      <%= image_tag @football_new.image.medium.url, class: "image_cicle" %>
    </div>
  <% end %>

  <div class="form-group submit_button">
    <%= f.submit t(".submit"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/football_news/_search_form.html.erb
<%= search_form_for @q, url: admin_football_news_index_path,
  class: "form-search" do |f| %>
  <div>
    <%= f.search_field :title_cont, class: "form-control col-sm-10 left", placeholder: t(".search") %>
    <%= f.submit t(".search_submit"), class: "btn btn-info search-submit" %>
    <div style="clear: both"></div>
  </div>
<% end %>

app/views/admin/football_news/edit.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title"><%= t ".edit_title" %></h4>
      </div>
      <div class="card-body ">
        <%= render partial: "form", locals: {url: admin_football_news_path(@football_new)} %>
      </div>
    </div>
  </div>
</div>

app/views/admin/football_news/index.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">
          <%= t ".football_news" %>
          <%= link_to t(".add_new"), new_admin_football_news_path, class: "btn btn-primary btn-xs right" %>
        </h4>
      </div>
      <div class="card-body">
        <%= render "search_form" %>
        <table class="table table-hover table-striped">
          <thead>
            <th>#</th>
            <th><%= t ".image" %></th>
            <th><%= t ".subject" %></th>
            <th><%= t ".time" %></th>
            <th><%= t ".action" %></th>
          </thead>
          <tbody>
            <%= render @football_news %>
          </tbody>
        </table>
        <%= paginate @football_news %>
      </div>
    </div>
  </div>
</div>

app/views/admin/football_news/new.html.erb
<% provide :title, t(".title") %>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header ">
        <h4 class="card-title"><%= t ".title" %></h4>
      </div>
      <div class="card-body ">
        <%= render partial: "form", locals: {url: "/admin/football_news"} %>
      </div>
    </div>
  </div>
</div>